#!/usr/bin/env bash

mkdir build

cd build

cmake \
    -DCMAKE_CXX_STANDARD=14 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DTUDAT_BUILD_TESTS=on \
    -DTUDAT_BUILD_WITH_ESTIMATION_TOOLS=off \
    -DTUDAT_BUILD_WITH_NRLMSISE00=on \
    -DTUDAT_BUILD_STATIC_LIBRARY=on \
    -DTUDAT_BUILD_TUDAT_TUTORIALS=off \
    -DTUDAT_BUILD_WITH_SOFA_INTERFACE=on \
    -DTUDAT_BUILD_WITH_SPICE_INTERFACE=on \
    -DTUDAT_BUILD_WITH_JSON_INTERFACE=off \
    -DTUDAT_SKIP_JSON_TESTS=on \
    -DBoost_NO_BOOST_CMAKE=on \
    -D_GLIBCXX_USE_CXX11_ABI=0 \
    ..

make -j2

ctest

make install
