github:
  user_or_org: elmarputs

channels:
  sources:
  - tudat-team
  - conda-forge
  - defaults
  
  targets:
  - [elmarputs, main]

provider:
  linux: azure
  osx: none
  win: none
  linux_ppc64le: None
  linux_aarch64: None

azure:
  # flag for forcing the building all supported providers
  force: False
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: True
  upload_packages: False
